Timestamp: 2025-08-13 17:46:30.102978
Context: edit_profile view for user gmadde
Exception: SocialLink() got unexpected keyword arguments: 'instance'

Traceback:
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Areis\aries\users\views.py", line 228, in edit_profile
    social_formset = SocialLink(request.POST, instance=profile)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Areis\aries_venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: SocialLink() got unexpected keyword arguments: 'instance'

